/** MENU ACTIONS */
export const GET_MENU = 'GET_MENU';

/** PRODUCT ACTIONS */
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

/** SHOPPING CART ACTIONS */
export const GET_SHOPPING_CART = 'GET_SHOPPING_CART';
export const ADD_SHOPPING_CART = 'ADD_SHOPPING_CART';
export const BUY_SHOPPING_CART = 'BUY_SHOPPING_CART';
export const DELETE_SHOPPING_ITEM = 'DELETE_SHOPPING_ITEM';
export const UPDATE_SHOPPING_ITEM = 'UPDATE_SHOPPING_ITEM';
export const SHOPPING_ITEMS_TOTALS = 'SHOPPING_ITEMS_TOTALS';